name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      run: cd backend && npm install

    - name: CI success message
      run: echo "✅ CI Pipeline passed"
